name: Build & Ship

on:
- push
- pull_request

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker
          
  node:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ !startsWith( github.ref, 'refs/tags' ) || startsWith( github.ref, 'refs/tags/node-') }}
    env:
      TAG_FILTER: refs/tags/node-${{matrix.node}}

    needs: setup
    strategy:
      matrix:
        context: [ "node-ci" ]
        node: [ "10", "12", "14" ]
    steps:
      - uses: actions/checkout@v2
      -
        name: Build node ${{matrix.context}}-${{matrix.node}}
        uses: docker/build-push-action@v2
        with:
          context: ${{matrix.context}}
          file: ${{matrix.context}}/${{matrix.node}}/Dockerfile
          tags: local-gh/${{matrix.context}}-${{matrix.node}}

      - uses: e1himself/goss-installation-action@v1.0.3
        with:
          version: v0.3.16

      - name: Test node ${{matrix.context}}-${{matrix.node}}
        env:
          GOSS_FILES_PATH: ${{matrix.context}}/${{matrix.node}}
          GOSS_FILES_STRATEGY: cp
        run: |
          dgoss run local-gh/${{matrix.context}}-${{matrix.node}} /bin/sleep 365d
      
      - name: Login to DockerHub
        if: startsWith(github.ref, env.TAG_FILTER)
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get tag name
        id: get_tag
        if: startsWith(github.ref, env.TAG_FILTER)
        run: |
          tag=`echo '${{github.ref}}' | sed -e 's.refs/tags/..'` ;
          echo "The tag is: $tag" ;
          echo "::set-output name=tag::$tag"

      - name: Push node ${{matrix.context}}-${{matrix.node}}
        if: startsWith(github.ref, env.TAG_FILTER)
        uses: docker/build-push-action@v2
        with:
          context: ${{matrix.context}}
          file: ${{matrix.context}}/${{matrix.node}}/Dockerfile
          tags: ushahidi/${{matrix.context}}:${{steps.get_tag.outputs.tag}}
          push: true

  php:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ !startsWith( github.ref, 'refs/tags' ) || startsWith( github.ref, 'refs/tags/php-') }}
    needs: setup
    env:
      TAG_FILTER: refs/tags/php-${{matrix.php}}
    strategy:
      matrix:
        context: [ "php-ci", "php-fpm-nginx" ]
        php: [ "7.2", "7.3", "7.4", "8.0" ]
    steps:
      - uses: actions/checkout@v2
      
      -
        name: Build php ${{matrix.context}}-${{matrix.php}}
        uses: docker/build-push-action@v2
        with:
          context: ${{matrix.context}}
          file: ${{matrix.context}}/${{matrix.php}}/Dockerfile
          tags: local-gh/${{matrix.context}}-${{matrix.php}}

      - uses: e1himself/goss-installation-action@v1.0.3
        with:
          version: v0.3.16

      - name: Test php ${{matrix.context}}-${{matrix.php}}
        env:
          GOSS_FILES_PATH: ${{matrix.context}}/${{matrix.php}}
          GOSS_FILES_STRATEGY: cp
        run: |
          dgoss run local-gh/${{matrix.context}}-${{matrix.php}} /bin/sleep 365d

      -
        name: Build php ${{matrix.context}}-${{matrix.php}} debug
        uses: docker/build-push-action@v2
        with:
          context: ${{matrix.context}}/debug
          build-args: |
            BASE_IMAGE=local-gh/${{matrix.context}}-${{matrix.php}}
          file: ${{matrix.context}}/debug/Dockerfile
          tags: local-gh/${{matrix.context}}-${{matrix.php}}-debug

      - name: Test php ${{matrix.context}}-${{matrix.php}} debug
        env:
          GOSS_FILES_PATH: ${{matrix.context}}/debug
          GOSS_FILES_STRATEGY: cp
        run: |
          dgoss run local-gh/${{matrix.context}}-${{matrix.php}}-debug /bin/sleep 365d

      - name: Login to DockerHub
        if: startsWith(github.ref, env.TAG_FILTER)
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get tag name
        id: get_tag
        if: startsWith(github.ref, env.TAG_FILTER)
        run: |
          tag=`echo '${{github.ref}}' | sed -e 's.refs/tags/..'` ;
          echo "The tag is: $tag" ;
          echo "::set-output name=tag::$tag"

      - name: Push php ${{matrix.context}}-${{matrix.php}}
        if: startsWith(github.ref, env.TAG_FILTER)
        uses: docker/build-push-action@v2
        with:
          context: ${{matrix.context}}
          file: ${{matrix.context}}/${{matrix.php}}/Dockerfile
          tags: ushahidi/${{matrix.context}}:${{steps.get_tag.outputs.tag}}
          push: true

      - name: Push php ${{matrix.context}}-${{matrix.php}} debug
        if: startsWith(github.ref, env.TAG_FILTER)
        uses: docker/build-push-action@v2
        with:
          context: ${{matrix.context}}/debug
          build-args: |
            BASE_IMAGE=local-gh/${{matrix.context}}-${{matrix.php}}
          file: ${{matrix.context}}/debug/Dockerfile
          tags: ushahidi/${{matrix.context}}:${{steps.get_tag.outputs.tag}}-debug
          push: true
